name: starling

image:
  repository: quay.io/reevoo/starling

pipeline:
  tests:
    spec:
      script: rake spec
    audit:
      script: |
        bundle exec bundle-audit check --update
        bundle exec ruby-audit check
