name: starling

image:
  repository: quay.io/reevoo/starling

pipeline:
  tests:
    spec:
      script: rake spec
      workdir: /usr/src
    outdated:
      script: bundle outdated
      workdir: /usr/src
    audit:
      script: |
        bundle exec bundle-audit check --update
        bundle exec ruby-audit check
      workdir: /usr/src
