# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{starling}
  s.version = "0.10.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Blaine Cook", "Chris Wanstrath", "Britt Selvitelle", "Glenn Rempe", "Abdul-Rahman Advany", "Seth Fitzsimmons", "Harm Aarts", "Chris Gaffney"]
  s.date = %q{2010-01-20}
  s.description = %q{Starling is a light-weight, persistent queue server that speaks the memcached protocol. It was originally developed for Twitter's backend.}
  s.email = ["blaine@twitter.com", "chris@ozmm.org", "abdulrahman@advany.com", "starlingmq@groups.google.com", "harmaarts@gmail.com", "gaffneyc@gmail.com"]
  s.executables = ["starling", "starling_top"]
  s.extra_rdoc_files = [
    "CHANGELOG",
     "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "bin/starling",
     "bin/starling_top",
     "etc/sample-config.yml",
     "etc/starling.redhat",
     "etc/starling.ubuntu",
     "lib/starling.rb",
     "lib/starling/handler.rb",
     "lib/starling/persistent_queue.rb",
     "lib/starling/queue_collection.rb",
     "lib/starling/server.rb",
     "lib/starling/server_runner.rb",
     "spec/starling_server_spec.rb",
     "starling.gemspec"
  ]
  s.homepage = %q{http://github.com/starling/starling/}
  s.rdoc_options = ["--quiet", "--title", "starling documentation", "--opname", "index.html", "--line-numbers", "--main", "README.rdoc", "--inline-source"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Starling is a lightweight, transactional, distributed queue server}
  s.test_files = [
    "spec/starling_server_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<memcache-client>, [">= 1.7.0"])
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.0"])
    else
      s.add_dependency(%q<memcache-client>, [">= 1.7.0"])
      s.add_dependency(%q<eventmachine>, [">= 0.12.0"])
    end
  else
    s.add_dependency(%q<memcache-client>, [">= 1.7.0"])
    s.add_dependency(%q<eventmachine>, [">= 0.12.0"])
  end
end

