# this file is automatically generated
Gem::Specification.new do |s|
  s.name = "starling"
  s.version = "0.9.9"
  s.authors = ["Blaine Cook", "Chris Wanstrath", "Britt Selvitelle", "Glenn Rempe", "Abdul-Rahman Advany", "Seth Fitzsimmons"]
  s.email = ["blaine@twitter.com", "chris@ozmm.org", "abdulrahman@advany.com", "starlingmq@groups.google.com"]
  s.homepage = "http://github.com/starling/starling/"
  s.summary = "Starling is a lightweight, transactional, distributed queue server"
  s.description = s.summary

  s.files = ["bin/starling", "bin/starling_top", "CHANGELOG", "etc/sample-config.yml", "etc/starling.redhat", "etc/starling.ubuntu", "lib/starling/handler.rb", "lib/starling/persistent_queue.rb", "lib/starling/queue_collection.rb", "lib/starling/server.rb", "lib/starling/server_runner.rb", "lib/starling.rb", "LICENSE", "Rakefile", "README.rdoc", "spec/starling_server_spec.rb"]
  s.executables = ["starling", "starling_top"]
  s.require_paths = ["lib"]

  s.has_rdoc = true
  s.rdoc_options = ["--quiet", "--title", "starling documentation", "--opname", "index.html", "--line-numbers", "--main", "README.rdoc", "--inline-source"]
  s.extra_rdoc_files = ["README.rdoc", "CHANGELOG", "LICENSE"]

  s.add_dependency 'memcache-client'
  s.add_dependency 'eventmachine', [">= 0.12.0"]
end
